// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1293: (x0,x1) => x0.append(x1),
      _1294: x0 => ({type: x0}),
      _1295: (x0,x1) => new Blob(x0,x1),
      _1296: x0 => globalThis.URL.createObjectURL(x0),
      _1297: (x0,x1) => x0.getElementById(x1),
      _1298: (x0,x1) => x0.createElement(x1),
      _1299: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1300: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1301: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1301(f,arguments.length,x0) }),
      _1302: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1303: x0 => x0.remove(),
      _1304: x0 => x0.click(),
      _1329: Date.now,
      _1331: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1332: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1333: () => new Error().stack,
      _1334: () => typeof dartUseDateNowForTicks !== "undefined",
      _1335: () => 1000 * performance.now(),
      _1336: () => Date.now(),
      _1337: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1338: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1339: () => new WeakMap(),
      _1340: (map, o) => map.get(o),
      _1341: (map, o, v) => map.set(o, v),
      _1342: (exn) => exn.toString(),
      _1343: (exn) => exn.stack,
      _1344: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1345: x0 => new WeakRef(x0),
      _1346: x0 => x0.deref(),
      _1347: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1347(f,arguments.length,x0) }),
      _1348: x0 => new FinalizationRegistry(x0),
      _1349: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _1351: (x0,x1) => x0.unregister(x1),
      _1353: () => globalThis.WeakRef,
      _1354: () => globalThis.FinalizationRegistry,
      _1356: x0 => x0.call(),
      _1357: s => JSON.stringify(s),
      _1358: s => printToConsole(s),
      _1359: (o, p, r) => o.replaceAll(p, () => r),
      _1360: (o, p, r) => o.replace(p, () => r),
      _1361: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1362: s => s.toUpperCase(),
      _1363: s => s.trim(),
      _1364: s => s.trimLeft(),
      _1365: s => s.trimRight(),
      _1366: (string, times) => string.repeat(times),
      _1367: Function.prototype.call.bind(String.prototype.indexOf),
      _1368: (s, p, i) => s.lastIndexOf(p, i),
      _1369: (string, token) => string.split(token),
      _1370: Object.is,
      _1373: (o, t) => typeof o === t,
      _1374: (o, c) => o instanceof c,
      _1375: o => Object.keys(o),
      _1388: (o, a) => o == a,
      _1405: x0 => new Array(x0),
      _1407: x0 => x0.length,
      _1409: (x0,x1) => x0[x1],
      _1410: (x0,x1,x2) => { x0[x1] = x2 },
      _1413: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1415: x0 => new Int8Array(x0),
      _1416: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1418: x0 => new Uint8ClampedArray(x0),
      _1420: x0 => new Int16Array(x0),
      _1422: x0 => new Uint16Array(x0),
      _1424: x0 => new Int32Array(x0),
      _1426: x0 => new Uint32Array(x0),
      _1428: x0 => new Float32Array(x0),
      _1430: x0 => new Float64Array(x0),
      _1451: (x0,x1) => x0.call(x1),
      _1454: x0 => x0.random(),
      _1455: (x0,x1) => x0.getRandomValues(x1),
      _1456: () => globalThis.crypto,
      _1457: () => globalThis.Math,
      _1470: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1471: (handle) => clearTimeout(handle),
      _1472: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1473: (handle) => clearInterval(handle),
      _1474: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1475: () => Date.now(),
      _1476: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1477: (x0,x1) => x0.exec(x1),
      _1478: (x0,x1) => x0.test(x1),
      _1479: x0 => x0.pop(),
      _1481: o => o === undefined,
      _1483: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1485: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1486: o => o instanceof RegExp,
      _1487: (l, r) => l === r,
      _1488: o => o,
      _1489: o => o,
      _1490: o => o,
      _1491: b => !!b,
      _1492: o => o.length,
      _1494: (o, i) => o[i],
      _1495: f => f.dartFunction,
      _1496: () => ({}),
      _1497: () => [],
      _1499: () => globalThis,
      _1500: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1501: (o, p) => p in o,
      _1502: (o, p) => o[p],
      _1503: (o, p, v) => o[p] = v,
      _1504: (o, m, a) => o[m].apply(o, a),
      _1506: o => String(o),
      _1507: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1508: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1508(f,arguments.length,x0) }),
      _1509: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1509(f,arguments.length,x0,x1) }),
      _1510: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1511: o => [o],
      _1512: (o0, o1) => [o0, o1],
      _1513: (o0, o1, o2) => [o0, o1, o2],
      _1514: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1515: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1516: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1517: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1518: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1519: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1520: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1521: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1522: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1523: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1524: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1525: x0 => new ArrayBuffer(x0),
      _1526: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1528: x0 => x0.index,
      _1529: x0 => x0.groups,
      _1530: x0 => x0.flags,
      _1531: x0 => x0.multiline,
      _1532: x0 => x0.ignoreCase,
      _1533: x0 => x0.unicode,
      _1534: x0 => x0.dotAll,
      _1535: (x0,x1) => { x0.lastIndex = x1 },
      _1536: (o, p) => p in o,
      _1537: (o, p) => o[p],
      _1538: (o, p, v) => o[p] = v,
      _1540: x0 => x0.exports,
      _1541: (x0,x1) => globalThis.WebAssembly.instantiateStreaming(x0,x1),
      _1542: x0 => x0.instance,
      _1544: x0 => new WebAssembly.Memory(x0),
      _1545: x0 => x0.buffer,
      _1548: x0 => x0.arrayBuffer(),
      _1550: x0 => x0.sqlite3_initialize,
      _1552: (x0,x1,x2,x3,x4) => x0.sqlite3_open_v2(x1,x2,x3,x4),
      _1553: (x0,x1) => x0.sqlite3_close_v2(x1),
      _1554: (x0,x1,x2) => x0.sqlite3_extended_result_codes(x1,x2),
      _1555: (x0,x1) => x0.sqlite3_extended_errcode(x1),
      _1556: (x0,x1) => x0.sqlite3_errmsg(x1),
      _1557: (x0,x1) => x0.sqlite3_errstr(x1),
      _1558: x0 => x0.sqlite3_error_offset,
      _1562: (x0,x1) => x0.sqlite3_last_insert_rowid(x1),
      _1563: (x0,x1) => x0.sqlite3_changes(x1),
      _1564: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_exec(x1,x2,x3,x4,x5),
      _1567: (x0,x1,x2,x3,x4,x5,x6) => x0.sqlite3_prepare_v3(x1,x2,x3,x4,x5,x6),
      _1568: (x0,x1) => x0.sqlite3_finalize(x1),
      _1569: (x0,x1) => x0.sqlite3_step(x1),
      _1570: (x0,x1) => x0.sqlite3_reset(x1),
      _1571: (x0,x1) => x0.sqlite3_stmt_isexplain(x1),
      _1573: (x0,x1) => x0.sqlite3_column_count(x1),
      _1574: (x0,x1) => x0.sqlite3_bind_parameter_count(x1),
      _1576: (x0,x1,x2) => x0.sqlite3_column_name(x1,x2),
      _1577: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_bind_blob64(x1,x2,x3,x4,x5),
      _1578: (x0,x1,x2,x3) => x0.sqlite3_bind_double(x1,x2,x3),
      _1579: (x0,x1,x2,x3) => x0.sqlite3_bind_int64(x1,x2,x3),
      _1580: (x0,x1,x2) => x0.sqlite3_bind_null(x1,x2),
      _1581: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_bind_text(x1,x2,x3,x4,x5),
      _1582: (x0,x1,x2) => x0.sqlite3_column_blob(x1,x2),
      _1583: (x0,x1,x2) => x0.sqlite3_column_double(x1,x2),
      _1584: (x0,x1,x2) => x0.sqlite3_column_int64(x1,x2),
      _1585: (x0,x1,x2) => x0.sqlite3_column_text(x1,x2),
      _1586: (x0,x1,x2) => x0.sqlite3_column_bytes(x1,x2),
      _1587: (x0,x1,x2) => x0.sqlite3_column_type(x1,x2),
      _1588: (x0,x1) => x0.sqlite3_value_blob(x1),
      _1589: (x0,x1) => x0.sqlite3_value_double(x1),
      _1590: (x0,x1) => x0.sqlite3_value_type(x1),
      _1591: (x0,x1) => x0.sqlite3_value_int64(x1),
      _1592: (x0,x1) => x0.sqlite3_value_text(x1),
      _1593: (x0,x1) => x0.sqlite3_value_bytes(x1),
      _1596: (x0,x1) => x0.sqlite3_user_data(x1),
      _1597: (x0,x1,x2,x3,x4) => x0.sqlite3_result_blob64(x1,x2,x3,x4),
      _1598: (x0,x1,x2) => x0.sqlite3_result_double(x1,x2),
      _1599: (x0,x1,x2,x3) => x0.sqlite3_result_error(x1,x2,x3),
      _1600: (x0,x1,x2) => x0.sqlite3_result_int64(x1,x2),
      _1601: (x0,x1) => x0.sqlite3_result_null(x1),
      _1602: (x0,x1,x2,x3,x4) => x0.sqlite3_result_text(x1,x2,x3,x4),
      _1603: x0 => x0.sqlite3_result_subtype,
      _1622: (x0,x1) => x0.dart_sqlite3_malloc(x1),
      _1623: (x0,x1) => x0.dart_sqlite3_free(x1),
      _1624: (x0,x1,x2,x3) => x0.dart_sqlite3_register_vfs(x1,x2,x3),
      _1625: (x0,x1,x2,x3,x4,x5) => x0.dart_sqlite3_create_scalar_function(x1,x2,x3,x4,x5),
      _1628: x0 => x0.dart_sqlite3_updates,
      _1629: x0 => x0.dart_sqlite3_commits,
      _1630: x0 => x0.dart_sqlite3_rollbacks,
      _1634: x0 => ({initial: x0}),
      _1635: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1635(f,arguments.length,x0) }),
      _1636: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1636(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1637: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1637(f,arguments.length,x0,x1,x2) }),
      _1638: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1638(f,arguments.length,x0,x1,x2,x3) }),
      _1639: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1639(f,arguments.length,x0,x1,x2,x3) }),
      _1640: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1640(f,arguments.length,x0,x1,x2) }),
      _1641: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1641(f,arguments.length,x0,x1) }),
      _1642: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1642(f,arguments.length,x0,x1) }),
      _1643: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1643(f,arguments.length,x0) }),
      _1644: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1644(f,arguments.length,x0) }),
      _1645: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1645(f,arguments.length,x0,x1,x2,x3) }),
      _1646: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1646(f,arguments.length,x0,x1,x2,x3) }),
      _1647: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1647(f,arguments.length,x0,x1) }),
      _1648: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1648(f,arguments.length,x0,x1) }),
      _1649: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1649(f,arguments.length,x0,x1) }),
      _1650: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1650(f,arguments.length,x0,x1) }),
      _1651: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1651(f,arguments.length,x0,x1) }),
      _1652: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1652(f,arguments.length,x0,x1) }),
      _1653: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1653(f,arguments.length,x0,x1,x2) }),
      _1654: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1654(f,arguments.length,x0,x1,x2) }),
      _1655: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1655(f,arguments.length,x0,x1,x2) }),
      _1656: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1656(f,arguments.length,x0) }),
      _1657: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1657(f,arguments.length,x0) }),
      _1658: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1658(f,arguments.length,x0) }),
      _1659: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1659(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1660: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1660(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1661: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1661(f,arguments.length,x0) }),
      _1662: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1662(f,arguments.length,x0) }),
      _1663: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1663(f,arguments.length,x0,x1) }),
      _1664: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1664(f,arguments.length,x0,x1) }),
      _1665: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1665(f,arguments.length,x0,x1,x2) }),
      _1667: (x0,x1,x2,x3) => x0.call(x1,x2,x3),
      _1672: x0 => new URL(x0),
      _1673: (x0,x1) => new URL(x0,x1),
      _1674: (x0,x1) => globalThis.fetch(x0,x1),
      _1675: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1676: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1678: (x0,x1) => ({i: x0,p: x1}),
      _1679: (x0,x1) => ({c: x0,r: x1}),
      _1680: x0 => x0.i,
      _1681: x0 => x0.p,
      _1682: x0 => x0.c,
      _1683: x0 => x0.r,
      _1684: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1684(f,arguments.length,x0) }),
      _1685: (x0,x1) => x0.postMessage(x1),
      _1686: x0 => x0.close(),
      _1688: x0 => new Worker(x0),
      _1690: x0 => x0.getDirectory(),
      _1691: x0 => ({create: x0}),
      _1692: (x0,x1,x2) => x0.getFileHandle(x1,x2),
      _1693: x0 => x0.createSyncAccessHandle(),
      _1694: x0 => x0.close(),
      _1697: x0 => x0.close(),
      _1700: (x0,x1,x2) => x0.open(x1,x2),
      _1704: (x0,x1,x2) => x0.getDirectoryHandle(x1,x2),
      _1709: x0 => ({create: x0}),
      _1714: (x0,x1) => new SharedWorker(x0,x1),
      _1715: x0 => x0.start(),
      _1716: x0 => x0.terminate(),
      _1717: () => new MessageChannel(),
      _1721: x0 => new SharedArrayBuffer(x0),
      _1722: x0 => ({at: x0}),
      _1723: x0 => x0.getSize(),
      _1724: (x0,x1) => x0.truncate(x1),
      _1725: x0 => x0.flush(),
      _1728: x0 => x0.synchronizationBuffer,
      _1729: x0 => x0.communicationBuffer,
      _1730: (x0,x1,x2,x3) => ({clientVersion: x0,root: x1,synchronizationBuffer: x2,communicationBuffer: x3}),
      _1731: (x0,x1) => globalThis.IDBKeyRange.bound(x0,x1),
      _1732: x0 => ({autoIncrement: x0}),
      _1733: (x0,x1,x2) => x0.createObjectStore(x1,x2),
      _1734: x0 => ({unique: x0}),
      _1735: (x0,x1,x2,x3) => x0.createIndex(x1,x2,x3),
      _1736: (x0,x1) => x0.createObjectStore(x1),
      _1737: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1737(f,arguments.length,x0) }),
      _1738: (x0,x1,x2) => x0.transaction(x1,x2),
      _1739: (x0,x1) => x0.objectStore(x1),
      _1741: (x0,x1) => x0.index(x1),
      _1742: x0 => x0.openKeyCursor(),
      _1743: (x0,x1) => x0.getKey(x1),
      _1744: (x0,x1) => ({name: x0,length: x1}),
      _1745: (x0,x1) => x0.put(x1),
      _1746: (x0,x1) => x0.get(x1),
      _1747: (x0,x1) => x0.openCursor(x1),
      _1748: x0 => globalThis.IDBKeyRange.only(x0),
      _1749: (x0,x1,x2) => x0.put(x1,x2),
      _1750: (x0,x1) => x0.update(x1),
      _1751: (x0,x1) => x0.delete(x1),
      _1752: x0 => x0.name,
      _1753: x0 => x0.length,
      _1756: x0 => x0.continue(),
      _1757: () => globalThis.indexedDB,
      _1758: () => globalThis.navigator,
      _1759: (x0,x1) => x0.read(x1),
      _1760: (x0,x1,x2) => x0.read(x1,x2),
      _1761: (x0,x1) => x0.write(x1),
      _1762: (x0,x1,x2) => x0.write(x1,x2),
      _1764: (x0,x1,x2) => globalThis.Atomics.wait(x0,x1,x2),
      _1766: (x0,x1,x2) => globalThis.Atomics.notify(x0,x1,x2),
      _1767: (x0,x1,x2) => globalThis.Atomics.store(x0,x1,x2),
      _1768: (x0,x1) => globalThis.Atomics.load(x0,x1),
      _1769: () => globalThis.Int32Array,
      _1771: () => globalThis.Uint8Array,
      _1773: () => globalThis.DataView,
      _1775: x0 => x0.byteLength,
      _1777: x0 => globalThis.BigInt(x0),
      _1778: x0 => globalThis.Number(x0),
      _1785: x0 => new BroadcastChannel(x0),
      _1786: x0 => globalThis.Array.isArray(x0),
      _1787: (x0,x1) => x0.postMessage(x1),
      _1789: (x0,x1) => ({kind: x0,table: x1}),
      _1790: x0 => x0.kind,
      _1791: x0 => x0.table,
      _1800: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1800(f,arguments.length,x0) }),
      _1801: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1801(f,arguments.length,x0) }),
      _1802: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1803: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1832: o => o instanceof Array,
      _1833: (a, i) => a.push(i),
      _1837: a => a.pop(),
      _1838: (a, i) => a.splice(i, 1),
      _1840: (a, s, e) => a.slice(s, e),
      _1843: a => a.length,
      _1845: (a, i) => a[i],
      _1846: (a, i, v) => a[i] = v,
      _1848: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1849: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1850: o => o instanceof DataView,
      _1851: o => o instanceof Uint8Array,
      _1852: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1853: o => o instanceof Int8Array,
      _1854: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1855: o => o instanceof Uint8ClampedArray,
      _1856: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1857: o => o instanceof Uint16Array,
      _1858: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1859: o => o instanceof Int16Array,
      _1860: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1861: o => o instanceof Uint32Array,
      _1862: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1863: o => o instanceof Int32Array,
      _1864: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1866: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1867: o => o instanceof Float32Array,
      _1868: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1869: o => o instanceof Float64Array,
      _1870: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1871: (t, s) => t.set(s),
      _1872: l => new DataView(new ArrayBuffer(l)),
      _1873: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1874: o => o.byteLength,
      _1875: o => o.buffer,
      _1876: o => o.byteOffset,
      _1877: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1878: (b, o) => new DataView(b, o),
      _1879: (b, o, l) => new DataView(b, o, l),
      _1880: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1881: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1882: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1883: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1884: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1885: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1886: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1887: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1888: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1889: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1890: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1891: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1894: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1895: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1896: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1897: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1898: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1899: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1900: Function.prototype.call.bind(Number.prototype.toString),
      _1901: Function.prototype.call.bind(BigInt.prototype.toString),
      _1902: Function.prototype.call.bind(Number.prototype.toString),
      _1903: (d, digits) => d.toFixed(digits),
      _2443: (x0,x1) => { x0.target = x1 },
      _2470: (x0,x1) => { x0.href = x1 },
      _3792: () => globalThis.window,
      _3833: x0 => x0.document,
      _3855: x0 => x0.navigator,
      _4244: x0 => x0.userAgent,
      _4257: x0 => x0.storage,
      _4295: x0 => x0.data,
      _4325: x0 => x0.port1,
      _4326: x0 => x0.port2,
      _4328: (x0,x1) => { x0.onmessage = x1 },
      _4406: x0 => x0.port,
      _6460: () => globalThis.document,
      _6541: x0 => x0.body,
      _6900: (x0,x1) => { x0.innerHTML = x1 },
      _10363: x0 => x0.result,
      _10364: x0 => x0.error,
      _10375: (x0,x1) => { x0.onupgradeneeded = x1 },
      _10377: x0 => x0.oldVersion,
      _10456: x0 => x0.key,
      _10457: x0 => x0.primaryKey,
      _10459: x0 => x0.value,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
